### ISSUE TITLE
Thank contributors in release notes and README

### ISSUE THREAD

**Issue by matthewpalmer** [matthewpalmer/Charter#37]
I want to cat the contents of contributors file onto the end of the readme, and make sure the contents of the contributors file goes out in the release notes for that version.

**Todo**
- [x] add contributors so far to the contributors file
- [x] write a script to do this
- [x] copy Moya's contributing guidelines/process (i.e. mention in readme that I'll give push access plus community guidelines too)

**Comment by matthewpalmer** [comment]
Added
